sensor:
  title: Sensor
  type: object
  description: Sensor's description and physical variables
  properties:
    id:
      description: Sensor identifier
      type: string
      format: uri
      example: urn:ngsi-ld:Sensor:[uuid]
      x-ngsi:
        type: Property    

    measurementVariable: 
        description: Defines the variable that the sensor can measure
            * `PM2.5` - Water consumption measurement
            * `Energy` - Energy consumption measurement
        type: string
        enum: 
            - PM2.5
            - PM10
            - CO2
            - O3
            - NO2
            - Sound
        example: PM10
        x-ngsi:
          uri: "http://morecolab.pt/pi/monAgroclimatica/dataModel/measurementVariable"
          uri-prefix: "http://morecolab.pt/pi/monAgroclimatica/dataModel/"
          type: Property

    measurementValue:
      description: Measured variable quantity consumed by a given asset, within a process
      minimum: 0
      type: number
      x-ngsi:
        uri: "http://morecolab.pt/pi/monAgroclimatica/dataModel/measurementValue"
        uri-prefix: "http://morecolab.pt/pi/monAgroclimatica/dataModel/"
        type: Property
        units: GQ [µm/m3], 2N [dB]

    belongsTo:
        anyOf:
            - description: 'Relationship property: Identifier format of any NGSI entity'
              maxLength: 256
              minLength: 1
              pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
              type: string
            - description: 'Relationship property: Identifier format of any NGSI entity'
              format: uri
              type: string
        description: 'Identification of the Measurement station the sensor is built in.'
        x-ngsi:
          uri: "http://morecolab.pt/pi/monAgroclimatica/dataModel/belongsTo"
          uri-prefix: "http://morecolab.pt/pi/monAgroclimatica/dataModel/"
          model: https://schema.org/URL
          type: Relationship

  required:
    - id
    - measurementVariable
    - measurementValue
    - belongsTo
    